  initStore([
    {
      id: 0,
      title: 'Arcane Realms (PC/PS5/Xbox)',
      description: 'Dive into a magical world filled with mythical creatures, ancient secrets.',
      price: 69.99,
      discountPrice: 54.99,
      image: 'images/service-1.jpg',
    },
    {
      id: 1,
      title: 'Speed Drift X (PS5)',
      description: 'Take on global circuits with realistic driving mechanics and stunning next-gen graphics.',
      price: 59.99,
      discountPrice: 49.99,
      image: 'images/service-2.jpg',
    },
    {
      id: 2,
      title: 'Dark Horizon (PC/PS5/Xbox)',
      description: 'Uncover the chilling mystery of a haunted town in this psychological adventure.',
      price: 69.99,
      discountPrice: 59.99,
      image: 'images/service-3.jpg',
    },
    {
      id: 3,
      title: 'Legends of Virelia (PS5)',
      description: 'Join a group of warriors on an emotional quest through a realm torn by war and fate.',
      price: 69.99,
      discountPrice: 59.99,
      image: 'images/service-4.jpg',
    },
    {
      id: 4,
      title: 'Kingdoms Awakened (PC/PS5)',
      description: 'Forge alliances, battle ancient foes, and shape your destiny in this turn-based RPG adventure.',
      price: 59.99,
      discountPrice: 49.99,
      image: 'images/service-5.jpg',
    },
    {
      id: 5,
      title: 'Shadow Spider: Rise (PS5)',
      description: 'Protect your city with high-speed web action and dynamic storytelling in this action-packed sequel.',
      price: 69.99,
      discountPrice: 59.99,
      image: 'images/service-6.jpg',
    },
  ]);
